import type { Metadata } from "next";
import { Outfit } from "next/font/google"; 
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const outfit = Outfit({
  weight: ["300", "400", "500", "600", "700"], 
  style: "normal",
  subsets: ["latin"], 
});

export const metadata: Metadata = {
  title: "Sistem Pengelolaan Data Customer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}<Toaster /></body>
    </html>
  );
}
